<?php
/**
 * ClientResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Vgrish\YclientsOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yclients
 *
 * yclients-openapi-php package for YCLIENTS generated based on the openapi schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vgrish\YclientsOpenApi\Model;

use ArrayAccess;
use Vgrish\YclientsOpenApi\ObjectSerializer;

/**
 * ClientResponse Class Doc Comment
 *
 * @category Class
 * @package  Vgrish\YclientsOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClientResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ClientResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'surname' => 'string',
        'patronymic' => 'string',
        'display_name' => 'string',
        'phone' => 'string',
        'email' => 'string',
        'card' => 'string',
        'birth_date' => 'string',
        'comment' => 'string',
        'discount' => 'int',
        'visits' => 'int',
        'sex_id' => 'int',
        'sex' => 'string',
        'sms_check' => 'int',
        'sms_bot' => 'int',
        'sms_not' => 'int',
        'spent' => 'int',
        'paid' => 'int',
        'balance' => 'int',
        'importance_id' => 'int',
        'importance' => 'string',
        'categories' => 'string[]',
        'last_change_date' => '\DateTime',
        'custom_fields' => 'map[string,object]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'surname' => null,
        'patronymic' => null,
        'display_name' => null,
        'phone' => null,
        'email' => null,
        'card' => null,
        'birth_date' => null,
        'comment' => null,
        'discount' => null,
        'visits' => null,
        'sex_id' => null,
        'sex' => null,
        'sms_check' => null,
        'sms_bot' => null,
        'sms_not' => null,
        'spent' => null,
        'paid' => null,
        'balance' => null,
        'importance_id' => null,
        'importance' => null,
        'categories' => null,
        'last_change_date' => 'date-time',
        'custom_fields' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'surname' => false,
        'patronymic' => false,
        'display_name' => false,
        'phone' => false,
        'email' => false,
        'card' => false,
        'birth_date' => false,
        'comment' => false,
        'discount' => false,
        'visits' => false,
        'sex_id' => false,
        'sex' => false,
        'sms_check' => false,
        'sms_bot' => false,
        'sms_not' => false,
        'spent' => false,
        'paid' => false,
        'balance' => false,
        'importance_id' => false,
        'importance' => false,
        'categories' => false,
        'last_change_date' => false,
        'custom_fields' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables() : array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull() : array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull) : void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property) : bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property) : bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'surname' => 'surname',
        'patronymic' => 'patronymic',
        'display_name' => 'display_name',
        'phone' => 'phone',
        'email' => 'email',
        'card' => 'card',
        'birth_date' => 'birth_date',
        'comment' => 'comment',
        'discount' => 'discount',
        'visits' => 'visits',
        'sex_id' => 'sex_id',
        'sex' => 'sex',
        'sms_check' => 'sms_check',
        'sms_bot' => 'sms_bot',
        'sms_not' => 'sms_not',
        'spent' => 'spent',
        'paid' => 'paid',
        'balance' => 'balance',
        'importance_id' => 'importance_id',
        'importance' => 'importance',
        'categories' => 'categories',
        'last_change_date' => 'last_change_date',
        'custom_fields' => 'custom_fields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'surname' => 'setSurname',
        'patronymic' => 'setPatronymic',
        'display_name' => 'setDisplayName',
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'card' => 'setCard',
        'birth_date' => 'setBirthDate',
        'comment' => 'setComment',
        'discount' => 'setDiscount',
        'visits' => 'setVisits',
        'sex_id' => 'setSexId',
        'sex' => 'setSex',
        'sms_check' => 'setSmsCheck',
        'sms_bot' => 'setSmsBot',
        'sms_not' => 'setSmsNot',
        'spent' => 'setSpent',
        'paid' => 'setPaid',
        'balance' => 'setBalance',
        'importance_id' => 'setImportanceId',
        'importance' => 'setImportance',
        'categories' => 'setCategories',
        'last_change_date' => 'setLastChangeDate',
        'custom_fields' => 'setCustomFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'surname' => 'getSurname',
        'patronymic' => 'getPatronymic',
        'display_name' => 'getDisplayName',
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'card' => 'getCard',
        'birth_date' => 'getBirthDate',
        'comment' => 'getComment',
        'discount' => 'getDiscount',
        'visits' => 'getVisits',
        'sex_id' => 'getSexId',
        'sex' => 'getSex',
        'sms_check' => 'getSmsCheck',
        'sms_bot' => 'getSmsBot',
        'sms_not' => 'getSmsNot',
        'spent' => 'getSpent',
        'paid' => 'getPaid',
        'balance' => 'getBalance',
        'importance_id' => 'getImportanceId',
        'importance' => 'getImportance',
        'categories' => 'getCategories',
        'last_change_date' => 'getLastChangeDate',
        'custom_fields' => 'getCustomFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('surname', $data ?? [], null);
        $this->setIfExists('patronymic', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('card', $data ?? [], null);
        $this->setIfExists('birth_date', $data ?? [], null);
        $this->setIfExists('comment', $data ?? [], null);
        $this->setIfExists('discount', $data ?? [], null);
        $this->setIfExists('visits', $data ?? [], null);
        $this->setIfExists('sex_id', $data ?? [], null);
        $this->setIfExists('sex', $data ?? [], null);
        $this->setIfExists('sms_check', $data ?? [], null);
        $this->setIfExists('sms_bot', $data ?? [], null);
        $this->setIfExists('sms_not', $data ?? [], null);
        $this->setIfExists('spent', $data ?? [], null);
        $this->setIfExists('paid', $data ?? [], null);
        $this->setIfExists('balance', $data ?? [], null);
        $this->setIfExists('importance_id', $data ?? [], null);
        $this->setIfExists('importance', $data ?? [], null);
        $this->setIfExists('categories', $data ?? [], null);
        $this->setIfExists('last_change_date', $data ?? [], null);
        $this->setIfExists('custom_fields', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue) : void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId() : int
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id ID клиента
     *
     * @return self
     */
    public function setId($id) : self
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName() : string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Имя клиента
     *
     * @return self
     */
    public function setName($name) : self
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets surname
     *
     * @return string|null
     */
    public function getSurname() : ?string
    {
        return $this->container['surname'];
    }

    /**
     * Sets surname
     *
     * @param string|null $surname Фамилия клиента
     *
     * @return self
     */
    public function setSurname($surname) : self
    {
        if (is_null($surname)) {
            throw new \InvalidArgumentException('non-nullable surname cannot be null');
        }
        $this->container['surname'] = $surname;

        return $this;
    }

    /**
     * Gets patronymic
     *
     * @return string|null
     */
    public function getPatronymic() : ?string
    {
        return $this->container['patronymic'];
    }

    /**
     * Sets patronymic
     *
     * @param string|null $patronymic Отчество клиента
     *
     * @return self
     */
    public function setPatronymic($patronymic) : self
    {
        if (is_null($patronymic)) {
            throw new \InvalidArgumentException('non-nullable patronymic cannot be null');
        }
        $this->container['patronymic'] = $patronymic;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName() : ?string
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name) : self
    {
        if (is_null($display_name)) {
            throw new \InvalidArgumentException('non-nullable display_name cannot be null');
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone() : ?string
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone Телефон клиента
     *
     * @return self
     */
    public function setPhone($phone) : self
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail() : ?string
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Email клиента
     *
     * @return self
     */
    public function setEmail($email) : self
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets card
     *
     * @return string|null
     */
    public function getCard() : ?string
    {
        return $this->container['card'];
    }

    /**
     * Sets card
     *
     * @param string|null $card Номер карты клиента
     *
     * @return self
     */
    public function setCard($card) : self
    {
        if (is_null($card)) {
            throw new \InvalidArgumentException('non-nullable card cannot be null');
        }
        $this->container['card'] = $card;

        return $this;
    }

    /**
     * Gets birth_date
     *
     * @return string|null
     */
    public function getBirthDate() : ?string
    {
        return $this->container['birth_date'];
    }

    /**
     * Sets birth_date
     *
     * @param string|null $birth_date Дата рождения клиента в формате yyyy-mm-dd
     *
     * @return self
     */
    public function setBirthDate($birth_date) : self
    {
        if (is_null($birth_date)) {
            throw new \InvalidArgumentException('non-nullable birth_date cannot be null');
        }
        $this->container['birth_date'] = $birth_date;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment() : ?string
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment Комментарий
     *
     * @return self
     */
    public function setComment($comment) : self
    {
        if (is_null($comment)) {
            throw new \InvalidArgumentException('non-nullable comment cannot be null');
        }
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return int|null
     */
    public function getDiscount() : ?int
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param int|null $discount Скидка клиента
     *
     * @return self
     */
    public function setDiscount($discount) : self
    {
        if (is_null($discount)) {
            throw new \InvalidArgumentException('non-nullable discount cannot be null');
        }
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets visits
     *
     * @return int|null
     */
    public function getVisits() : ?int
    {
        return $this->container['visits'];
    }

    /**
     * Sets visits
     *
     * @param int|null $visits visits
     *
     * @return self
     */
    public function setVisits($visits) : self
    {
        if (is_null($visits)) {
            throw new \InvalidArgumentException('non-nullable visits cannot be null');
        }
        $this->container['visits'] = $visits;

        return $this;
    }

    /**
     * Gets sex_id
     *
     * @return int|null
     */
    public function getSexId() : ?int
    {
        return $this->container['sex_id'];
    }

    /**
     * Sets sex_id
     *
     * @param int|null $sex_id Пол клиента (1 - мужской, 2 - женский, 0 - не известен)
     *
     * @return self
     */
    public function setSexId($sex_id) : self
    {
        if (is_null($sex_id)) {
            throw new \InvalidArgumentException('non-nullable sex_id cannot be null');
        }
        $this->container['sex_id'] = $sex_id;

        return $this;
    }

    /**
     * Gets sex
     *
     * @return string|null
     */
    public function getSex() : ?string
    {
        return $this->container['sex'];
    }

    /**
     * Sets sex
     *
     * @param string|null $sex sex
     *
     * @return self
     */
    public function setSex($sex) : self
    {
        if (is_null($sex)) {
            throw new \InvalidArgumentException('non-nullable sex cannot be null');
        }
        $this->container['sex'] = $sex;

        return $this;
    }

    /**
     * Gets sms_check
     *
     * @return int|null
     */
    public function getSmsCheck() : ?int
    {
        return $this->container['sms_check'];
    }

    /**
     * Sets sms_check
     *
     * @param int|null $sms_check 1 - Поздравлять с Днем Рождения по SMS, 0 - не поздравлять
     *
     * @return self
     */
    public function setSmsCheck($sms_check) : self
    {
        if (is_null($sms_check)) {
            throw new \InvalidArgumentException('non-nullable sms_check cannot be null');
        }
        $this->container['sms_check'] = $sms_check;

        return $this;
    }

    /**
     * Gets sms_bot
     *
     * @return int|null
     */
    public function getSmsBot() : ?int
    {
        return $this->container['sms_bot'];
    }

    /**
     * Sets sms_bot
     *
     * @param int|null $sms_bot sms_bot
     *
     * @return self
     */
    public function setSmsBot($sms_bot) : self
    {
        if (is_null($sms_bot)) {
            throw new \InvalidArgumentException('non-nullable sms_bot cannot be null');
        }
        $this->container['sms_bot'] = $sms_bot;

        return $this;
    }

    /**
     * Gets sms_not
     *
     * @return int|null
     */
    public function getSmsNot() : ?int
    {
        return $this->container['sms_not'];
    }

    /**
     * Sets sms_not
     *
     * @param int|null $sms_not 1 - Исключить клиента из SMS рассылок, 0 - не исключать
     *
     * @return self
     */
    public function setSmsNot($sms_not) : self
    {
        if (is_null($sms_not)) {
            throw new \InvalidArgumentException('non-nullable sms_not cannot be null');
        }
        $this->container['sms_not'] = $sms_not;

        return $this;
    }

    /**
     * Gets spent
     *
     * @return int|null
     */
    public function getSpent() : ?int
    {
        return $this->container['spent'];
    }

    /**
     * Sets spent
     *
     * @param int|null $spent Сколько потратил средств в компании на момент добавления
     *
     * @return self
     */
    public function setSpent($spent) : self
    {
        if (is_null($spent)) {
            throw new \InvalidArgumentException('non-nullable spent cannot be null');
        }
        $this->container['spent'] = $spent;

        return $this;
    }

    /**
     * Gets paid
     *
     * @return int|null
     */
    public function getPaid() : ?int
    {
        return $this->container['paid'];
    }

    /**
     * Sets paid
     *
     * @param int|null $paid paid
     *
     * @return self
     */
    public function setPaid($paid) : self
    {
        if (is_null($paid)) {
            throw new \InvalidArgumentException('non-nullable paid cannot be null');
        }
        $this->container['paid'] = $paid;

        return $this;
    }

    /**
     * Gets balance
     *
     * @return int|null
     */
    public function getBalance() : ?int
    {
        return $this->container['balance'];
    }

    /**
     * Sets balance
     *
     * @param int|null $balance Баланс клиента
     *
     * @return self
     */
    public function setBalance($balance) : self
    {
        if (is_null($balance)) {
            throw new \InvalidArgumentException('non-nullable balance cannot be null');
        }
        $this->container['balance'] = $balance;

        return $this;
    }

    /**
     * Gets importance_id
     *
     * @return int|null
     */
    public function getImportanceId() : ?int
    {
        return $this->container['importance_id'];
    }

    /**
     * Sets importance_id
     *
     * @param int|null $importance_id Класс важности клиента (0 - нет, 1 - бронза, 2 - серебро, 3 - золото)
     *
     * @return self
     */
    public function setImportanceId($importance_id) : self
    {
        if (is_null($importance_id)) {
            throw new \InvalidArgumentException('non-nullable importance_id cannot be null');
        }
        $this->container['importance_id'] = $importance_id;

        return $this;
    }

    /**
     * Gets importance
     *
     * @return string|null
     */
    public function getImportance() : ?string
    {
        return $this->container['importance'];
    }

    /**
     * Sets importance
     *
     * @param string|null $importance importance
     *
     * @return self
     */
    public function setImportance($importance) : self
    {
        if (is_null($importance)) {
            throw new \InvalidArgumentException('non-nullable importance cannot be null');
        }
        $this->container['importance'] = $importance;

        return $this;
    }

    /**
     * Gets categories
     *
     * @return string[]|null
     */
    public function getCategories() : ?array
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     *
     * @param string[]|null $categories categories
     *
     * @return self
     */
    public function setCategories($categories) : self
    {
        if (is_null($categories)) {
            throw new \InvalidArgumentException('non-nullable categories cannot be null');
        }
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets last_change_date
     *
     * @return \DateTime|null
     */
    public function getLastChangeDate() : ?\DateTime
    {
        return $this->container['last_change_date'];
    }

    /**
     * Sets last_change_date
     *
     * @param \DateTime|null $last_change_date last_change_date
     *
     * @return self
     */
    public function setLastChangeDate($last_change_date) : self
    {
        if (is_null($last_change_date)) {
            throw new \InvalidArgumentException('non-nullable last_change_date cannot be null');
        }
        $this->container['last_change_date'] = $last_change_date;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return map[string,object]|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param map[string,object]|null $custom_fields Массив дополнительных полей клиента в виде пар \"api-key\": \"value\"
     *
     * @return self
     */
    public function setCustomFields($custom_fields) : self
    {
        if (is_null($custom_fields)) {
            throw new \InvalidArgumentException('non-nullable custom_fields cannot be null');
        }
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }


    /**
    * Gets array presentation of the object
    *
    * @return array
    */
    public function toArray() : array
    {
        return json_decode(json_encode(ObjectSerializer::sanitizeForSerialization($this)), true);
    }

}


