<?php
/**
 * ClientUpdateRequest
 *
 * @category Class
 * @package  Vgrish\YclientsOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yclients
 *
 * yclients-openapi-php package for YCLIENTS generated based on the openapi schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vgrish\YclientsOpenApi\Model;

use ArrayAccess;
use Vgrish\YclientsOpenApi\ObjectSerializer;

/**
 * ClientUpdateRequest Class Doc Comment
 *
 * @category Class
 * @package  Vgrish\YclientsOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClientUpdateRequest implements ModelInterface, ArrayAccess
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ClientUpdateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'phone' => 'string',
        'surname' => 'string',
        'patronymic' => 'string',
        'email' => 'string',
        'sex_id' => 'string',
        'importance_id' => 'string',
        'discount' => 'string',
        'card' => 'string',
        'birth_date' => 'string',
        'comment' => 'string',
        'spent' => 'string',
        'balance' => 'string',
        'sms_check' => 'string',
        'sms_not' => 'string',
        'labels' => 'object',
        'custom_fields' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'name' => null,
        'phone' => null,
        'surname' => null,
        'patronymic' => null,
        'email' => null,
        'sex_id' => null,
        'importance_id' => null,
        'discount' => null,
        'card' => null,
        'birth_date' => null,
        'comment' => null,
        'spent' => null,
        'balance' => null,
        'sms_check' => null,
        'sms_not' => null,
        'labels' => null,
        'custom_fields' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'phone' => 'phone',
        'surname' => 'surname',
        'patronymic' => 'patronymic',
        'email' => 'email',
        'sex_id' => 'sex_id',
        'importance_id' => 'importance_id',
        'discount' => 'discount',
        'card' => 'card',
        'birth_date' => 'birth_date',
        'comment' => 'comment',
        'spent' => 'spent',
        'balance' => 'balance',
        'sms_check' => 'sms_check',
        'sms_not' => 'sms_not',
        'labels' => 'labels',
        'custom_fields' => 'custom_fields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'phone' => 'setPhone',
        'surname' => 'setSurname',
        'patronymic' => 'setPatronymic',
        'email' => 'setEmail',
        'sex_id' => 'setSexId',
        'importance_id' => 'setImportanceId',
        'discount' => 'setDiscount',
        'card' => 'setCard',
        'birth_date' => 'setBirthDate',
        'comment' => 'setComment',
        'spent' => 'setSpent',
        'balance' => 'setBalance',
        'sms_check' => 'setSmsCheck',
        'sms_not' => 'setSmsNot',
        'labels' => 'setLabels',
        'custom_fields' => 'setCustomFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'phone' => 'getPhone',
        'surname' => 'getSurname',
        'patronymic' => 'getPatronymic',
        'email' => 'getEmail',
        'sex_id' => 'getSexId',
        'importance_id' => 'getImportanceId',
        'discount' => 'getDiscount',
        'card' => 'getCard',
        'birth_date' => 'getBirthDate',
        'comment' => 'getComment',
        'spent' => 'getSpent',
        'balance' => 'getBalance',
        'sms_check' => 'getSmsCheck',
        'sms_not' => 'getSmsNot',
        'labels' => 'getLabels',
        'custom_fields' => 'getCustomFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }





    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['surname'] = isset($data['surname']) ? $data['surname'] : null;
        $this->container['patronymic'] = isset($data['patronymic']) ? $data['patronymic'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['sex_id'] = isset($data['sex_id']) ? $data['sex_id'] : null;
        $this->container['importance_id'] = isset($data['importance_id']) ? $data['importance_id'] : null;
        $this->container['discount'] = isset($data['discount']) ? $data['discount'] : null;
        $this->container['card'] = isset($data['card']) ? $data['card'] : null;
        $this->container['birth_date'] = isset($data['birth_date']) ? $data['birth_date'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['spent'] = isset($data['spent']) ? $data['spent'] : null;
        $this->container['balance'] = isset($data['balance']) ? $data['balance'] : null;
        $this->container['sms_check'] = isset($data['sms_check']) ? $data['sms_check'] : null;
        $this->container['sms_not'] = isset($data['sms_not']) ? $data['sms_not'] : null;
        $this->container['labels'] = isset($data['labels']) ? $data['labels'] : null;
        $this->container['custom_fields'] = isset($data['custom_fields']) ? $data['custom_fields'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName() : string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Имя клиента
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone() : string
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone Телефон клиента
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets surname
     *
     * @return string|null
     */
    public function getSurname() : ?string
    {
        return $this->container['surname'];
    }

    /**
     * Sets surname
     *
     * @param string|null $surname surname
     *
     * @return $this
     */
    public function setSurname($surname)
    {
        $this->container['surname'] = $surname;

        return $this;
    }

    /**
     * Gets patronymic
     *
     * @return string|null
     */
    public function getPatronymic() : ?string
    {
        return $this->container['patronymic'];
    }

    /**
     * Sets patronymic
     *
     * @param string|null $patronymic patronymic
     *
     * @return $this
     */
    public function setPatronymic($patronymic)
    {
        $this->container['patronymic'] = $patronymic;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail() : ?string
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets sex_id
     *
     * @return string|null
     */
    public function getSexId() : ?string
    {
        return $this->container['sex_id'];
    }

    /**
     * Sets sex_id
     *
     * @param string|null $sex_id sex_id
     *
     * @return $this
     */
    public function setSexId($sex_id)
    {
        $this->container['sex_id'] = $sex_id;

        return $this;
    }

    /**
     * Gets importance_id
     *
     * @return string|null
     */
    public function getImportanceId() : ?string
    {
        return $this->container['importance_id'];
    }

    /**
     * Sets importance_id
     *
     * @param string|null $importance_id importance_id
     *
     * @return $this
     */
    public function setImportanceId($importance_id)
    {
        $this->container['importance_id'] = $importance_id;

        return $this;
    }

    /**
     * Gets discount
     *
     * @return string|null
     */
    public function getDiscount() : ?string
    {
        return $this->container['discount'];
    }

    /**
     * Sets discount
     *
     * @param string|null $discount discount
     *
     * @return $this
     */
    public function setDiscount($discount)
    {
        $this->container['discount'] = $discount;

        return $this;
    }

    /**
     * Gets card
     *
     * @return string|null
     */
    public function getCard() : ?string
    {
        return $this->container['card'];
    }

    /**
     * Sets card
     *
     * @param string|null $card card
     *
     * @return $this
     */
    public function setCard($card)
    {
        $this->container['card'] = $card;

        return $this;
    }

    /**
     * Gets birth_date
     *
     * @return string|null
     */
    public function getBirthDate() : ?string
    {
        return $this->container['birth_date'];
    }

    /**
     * Sets birth_date
     *
     * @param string|null $birth_date birth_date
     *
     * @return $this
     */
    public function setBirthDate($birth_date)
    {
        $this->container['birth_date'] = $birth_date;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string|null
     */
    public function getComment() : ?string
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string|null $comment comment
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets spent
     *
     * @return string|null
     */
    public function getSpent() : ?string
    {
        return $this->container['spent'];
    }

    /**
     * Sets spent
     *
     * @param string|null $spent spent
     *
     * @return $this
     */
    public function setSpent($spent)
    {
        $this->container['spent'] = $spent;

        return $this;
    }

    /**
     * Gets balance
     *
     * @return string|null
     */
    public function getBalance() : ?string
    {
        return $this->container['balance'];
    }

    /**
     * Sets balance
     *
     * @param string|null $balance balance
     *
     * @return $this
     */
    public function setBalance($balance)
    {
        $this->container['balance'] = $balance;

        return $this;
    }

    /**
     * Gets sms_check
     *
     * @return string|null
     */
    public function getSmsCheck() : ?string
    {
        return $this->container['sms_check'];
    }

    /**
     * Sets sms_check
     *
     * @param string|null $sms_check sms_check
     *
     * @return $this
     */
    public function setSmsCheck($sms_check)
    {
        $this->container['sms_check'] = $sms_check;

        return $this;
    }

    /**
     * Gets sms_not
     *
     * @return string|null
     */
    public function getSmsNot() : ?string
    {
        return $this->container['sms_not'];
    }

    /**
     * Sets sms_not
     *
     * @param string|null $sms_not sms_not
     *
     * @return $this
     */
    public function setSmsNot($sms_not)
    {
        $this->container['sms_not'] = $sms_not;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return object|null
     */
    public function getLabels() : ?object
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param object|null $labels labels
     *
     * @return $this
     */
    public function setLabels($labels)
    {
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields() : ?object
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields custom_fields
     *
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset) : mixed
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets array presentation of the object
     *
     * @return array
     */
    public function toArray() : array
    {
        $array = [];
        foreach ($this->container as $key => $value) {
            if (is_a($value, ModelInterface::class)) {
                $array[$key] = $value->toArray();
            } else {
                $array[$key] = $value;
            }
        }
        return $array;
    }

}


