<?php
/**
 * CompanyCreateRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Vgrish\YclientsOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yclients
 *
 * yclients-openapi-php package for YCLIENTS generated based on the openapi schema
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vgrish\YclientsOpenApi\Model;

use ArrayAccess;
use Vgrish\YclientsOpenApi\ObjectSerializer;

/**
 * CompanyCreateRequest Class Doc Comment
 *
 * @category Class
 * @description Создать компанию
 * @package  Vgrish\YclientsOpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CompanyCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CompanyCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'title' => 'string',
        'country_id' => 'int',
        'city_id' => 'int',
        'address' => 'string',
        'site' => 'string',
        'coordinate_lat' => 'string',
        'coordinate_lot' => 'string',
        'business_type_id' => 'int',
        'short_descr' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'title' => null,
        'country_id' => null,
        'city_id' => null,
        'address' => null,
        'site' => null,
        'coordinate_lat' => null,
        'coordinate_lot' => null,
        'business_type_id' => null,
        'short_descr' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'title' => false,
        'country_id' => false,
        'city_id' => false,
        'address' => false,
        'site' => false,
        'coordinate_lat' => false,
        'coordinate_lot' => false,
        'business_type_id' => false,
        'short_descr' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables() : array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull() : array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull) : void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property) : bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property) : bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'title' => 'title',
        'country_id' => 'country_id',
        'city_id' => 'city_id',
        'address' => 'address',
        'site' => 'site',
        'coordinate_lat' => 'coordinate_lat',
        'coordinate_lot' => 'coordinate_lot',
        'business_type_id' => 'business_type_id',
        'short_descr' => 'short_descr'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'title' => 'setTitle',
        'country_id' => 'setCountryId',
        'city_id' => 'setCityId',
        'address' => 'setAddress',
        'site' => 'setSite',
        'coordinate_lat' => 'setCoordinateLat',
        'coordinate_lot' => 'setCoordinateLot',
        'business_type_id' => 'setBusinessTypeId',
        'short_descr' => 'setShortDescr'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'title' => 'getTitle',
        'country_id' => 'getCountryId',
        'city_id' => 'getCityId',
        'address' => 'getAddress',
        'site' => 'getSite',
        'coordinate_lat' => 'getCoordinateLat',
        'coordinate_lot' => 'getCoordinateLot',
        'business_type_id' => 'getBusinessTypeId',
        'short_descr' => 'getShortDescr'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('country_id', $data ?? [], null);
        $this->setIfExists('city_id', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('site', $data ?? [], null);
        $this->setIfExists('coordinate_lat', $data ?? [], null);
        $this->setIfExists('coordinate_lot', $data ?? [], null);
        $this->setIfExists('business_type_id', $data ?? [], null);
        $this->setIfExists('short_descr', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue) : void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties() : array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid() : bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle() : ?string
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Название компании
     *
     * @return self
     */
    public function setTitle($title) : self
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets country_id
     *
     * @return int|null
     */
    public function getCountryId() : ?int
    {
        return $this->container['country_id'];
    }

    /**
     * Sets country_id
     *
     * @param int|null $country_id Идентификатор страны, в которой расположена копания ([метод получения стран](#countries))
     *
     * @return self
     */
    public function setCountryId($country_id) : self
    {
        if (is_null($country_id)) {
            throw new \InvalidArgumentException('non-nullable country_id cannot be null');
        }
        $this->container['country_id'] = $country_id;

        return $this;
    }

    /**
     * Gets city_id
     *
     * @return int|null
     */
    public function getCityId() : ?int
    {
        return $this->container['city_id'];
    }

    /**
     * Sets city_id
     *
     * @param int|null $city_id Идентификатор города, в котором расположена компания ([метод получения городов](#cities))
     *
     * @return self
     */
    public function setCityId($city_id) : self
    {
        if (is_null($city_id)) {
            throw new \InvalidArgumentException('non-nullable city_id cannot be null');
        }
        $this->container['city_id'] = $city_id;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string|null
     */
    public function getAddress() : ?string
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string|null $address Адрес компании
     *
     * @return self
     */
    public function setAddress($address) : self
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets site
     *
     * @return string|null
     */
    public function getSite() : ?string
    {
        return $this->container['site'];
    }

    /**
     * Sets site
     *
     * @param string|null $site Сайт компании
     *
     * @return self
     */
    public function setSite($site) : self
    {
        if (is_null($site)) {
            throw new \InvalidArgumentException('non-nullable site cannot be null');
        }
        $this->container['site'] = $site;

        return $this;
    }

    /**
     * Gets coordinate_lat
     *
     * @return string|null
     */
    public function getCoordinateLat() : ?string
    {
        return $this->container['coordinate_lat'];
    }

    /**
     * Sets coordinate_lat
     *
     * @param string|null $coordinate_lat Широта
     *
     * @return self
     */
    public function setCoordinateLat($coordinate_lat) : self
    {
        if (is_null($coordinate_lat)) {
            throw new \InvalidArgumentException('non-nullable coordinate_lat cannot be null');
        }
        $this->container['coordinate_lat'] = $coordinate_lat;

        return $this;
    }

    /**
     * Gets coordinate_lot
     *
     * @return string|null
     */
    public function getCoordinateLot() : ?string
    {
        return $this->container['coordinate_lot'];
    }

    /**
     * Sets coordinate_lot
     *
     * @param string|null $coordinate_lot Долгота
     *
     * @return self
     */
    public function setCoordinateLot($coordinate_lot) : self
    {
        if (is_null($coordinate_lot)) {
            throw new \InvalidArgumentException('non-nullable coordinate_lot cannot be null');
        }
        $this->container['coordinate_lot'] = $coordinate_lot;

        return $this;
    }

    /**
     * Gets business_type_id
     *
     * @return int|null
     */
    public function getBusinessTypeId() : ?int
    {
        return $this->container['business_type_id'];
    }

    /**
     * Sets business_type_id
     *
     * @param int|null $business_type_id Сфера бизнеса
     *
     * @return self
     */
    public function setBusinessTypeId($business_type_id) : self
    {
        if (is_null($business_type_id)) {
            throw new \InvalidArgumentException('non-nullable business_type_id cannot be null');
        }
        $this->container['business_type_id'] = $business_type_id;

        return $this;
    }

    /**
     * Gets short_descr
     *
     * @return string|null
     */
    public function getShortDescr() : ?string
    {
        return $this->container['short_descr'];
    }

    /**
     * Sets short_descr
     *
     * @param string|null $short_descr Категория компании
     *
     * @return self
     */
    public function setShortDescr($short_descr) : self
    {
        if (is_null($short_descr)) {
            throw new \InvalidArgumentException('non-nullable short_descr cannot be null');
        }
        $this->container['short_descr'] = $short_descr;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }


    /**
    * Gets array presentation of the object
    *
    * @return array
    */
    public function toArray() : array
    {
        return json_decode(json_encode(ObjectSerializer::sanitizeForSerialization($this)), true);
    }

}


